version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:6.0
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-container
    build: .
    image: clean-node-api #como fiz build essa image diz respeito ao nome da tag
    restart: always
    command: npm debug #opcional, caso use aqui remove no dockerfile
    volumes: #substitui o COPY, pois o mesmo guarda cache e pode não atualizar o /dist
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports: #como é build, no dockerfile pode tirar o EXPOSE
      - '3333:3333'
      - '9222:9222'
